/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author utt
 */
public class ViewAbout extends javax.swing.JPanel {

    /**
     * Creates new form ViewConverter
     */
    public ViewAbout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BackGround = new javax.swing.JPanel();
        JL_Title = new javax.swing.JLabel();
        JL_Name = new javax.swing.JLabel();
        JL_Mail = new javax.swing.JLabel();
        JL_Description = new javax.swing.JLabel();
        JP_Col = new javax.swing.JPanel();

        JP_BackGround.setBackground(new java.awt.Color(255, 255, 255));
        JP_BackGround.setForeground(new java.awt.Color(255, 255, 255));

        JL_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL_Title.setText("Acerca de");

        JL_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Name.setText("Raúl Prior García");

        JL_Mail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Mail.setText("1715110187@utec-tgo.edu.mx");

        JL_Description.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Description.setText("Aplicacion que integra practicas MVC");

        JP_Col.setBackground(new java.awt.Color(0, 204, 204));
        JP_Col.setForeground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout JP_ColLayout = new javax.swing.GroupLayout(JP_Col);
        JP_Col.setLayout(JP_ColLayout);
        JP_ColLayout.setHorizontalGroup(
            JP_ColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        JP_ColLayout.setVerticalGroup(
            JP_ColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JP_BackGroundLayout = new javax.swing.GroupLayout(JP_BackGround);
        JP_BackGround.setLayout(JP_BackGroundLayout);
        JP_BackGroundLayout.setHorizontalGroup(
            JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JP_Col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BackGroundLayout.createSequentialGroup()
                        .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(JL_Mail))
                            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JL_Description)))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BackGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(JL_Name))
                            .addComponent(JL_Title))
                        .addGap(98, 98, 98))))
        );
        JP_BackGroundLayout.setVerticalGroup(
            JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(JL_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Name)
                .addGap(18, 18, 18)
                .addComponent(JL_Mail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_Description)
                .addContainerGap())
            .addComponent(JP_Col, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Description;
    private javax.swing.JLabel JL_Mail;
    private javax.swing.JLabel JL_Name;
    private javax.swing.JLabel JL_Title;
    private javax.swing.JPanel JP_BackGround;
    private javax.swing.JPanel JP_Col;
    // End of variables declaration//GEN-END:variables
}
