/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author utt
 */
public class ViewConverter extends javax.swing.JPanel {

    /**
     * Creates new form ViewAbout
     */
    public ViewConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_BackGround = new javax.swing.JPanel();
        JBtn_Converter = new javax.swing.JButton();
        JCBox_System = new javax.swing.JComboBox<>();
        JL_Result = new javax.swing.JLabel();
        JTF_Result = new javax.swing.JTextField();
        JTF_Decimal = new javax.swing.JTextField();
        JL_Decimal = new javax.swing.JLabel();
        JP_Col = new javax.swing.JPanel();
        JL_ErrorDecimal = new javax.swing.JLabel();

        JP_BackGround.setBackground(new java.awt.Color(255, 255, 255));

        JBtn_Converter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBtn_Converter.setText("Convertir");

        JCBox_System.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCBox_System.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binario", "Octal", "Hexadecimal" }));
        JCBox_System.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBox_SystemActionPerformed(evt);
            }
        });

        JL_Result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Result.setText("Resultado");

        JTF_Result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTF_Result.setText(" ");
        JTF_Result.setEnabled(false);

        JTF_Decimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JL_Decimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Decimal.setText("Decimal");

        JP_Col.setBackground(new java.awt.Color(0, 204, 204));
        JP_Col.setForeground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout JP_ColLayout = new javax.swing.GroupLayout(JP_Col);
        JP_Col.setLayout(JP_ColLayout);
        JP_ColLayout.setHorizontalGroup(
            JP_ColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        JP_ColLayout.setVerticalGroup(
            JP_ColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        JL_ErrorDecimal.setForeground(new java.awt.Color(210, 28, 28));
        JL_ErrorDecimal.setText("Sólo numeros enteros");

        javax.swing.GroupLayout JP_BackGroundLayout = new javax.swing.GroupLayout(JP_BackGround);
        JP_BackGround.setLayout(JP_BackGroundLayout);
        JP_BackGroundLayout.setHorizontalGroup(
            JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_BackGroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JP_Col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_BackGroundLayout.createSequentialGroup()
                        .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_Decimal)
                            .addComponent(JL_Result))
                        .addGap(26, 26, 26)
                        .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTF_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_ErrorDecimal)))
                    .addGroup(JP_BackGroundLayout.createSequentialGroup()
                        .addComponent(JCBox_System, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(JBtn_Converter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_BackGroundLayout.setVerticalGroup(
            JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Decimal)
                    .addComponent(JTF_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_ErrorDecimal)
                .addGap(54, 54, 54)
                .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_Result)
                    .addComponent(JTF_Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(JP_BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBox_System, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtn_Converter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JP_BackGroundLayout.createSequentialGroup()
                .addComponent(JP_Col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JCBox_SystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBox_SystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBox_SystemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBtn_Converter;
    public javax.swing.JComboBox<String> JCBox_System;
    public javax.swing.JLabel JL_Decimal;
    public javax.swing.JLabel JL_ErrorDecimal;
    public javax.swing.JLabel JL_Result;
    private javax.swing.JPanel JP_BackGround;
    private javax.swing.JPanel JP_Col;
    public javax.swing.JTextField JTF_Decimal;
    public javax.swing.JTextField JTF_Result;
    // End of variables declaration//GEN-END:variables
}
