/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author panda
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtnG_Menu = new javax.swing.ButtonGroup();
        JMenuBar = new javax.swing.JMenuBar();
        JMenu = new javax.swing.JMenu();
        JRBtn_About = new javax.swing.JRadioButtonMenuItem();
        JRBtn_Arithmetic = new javax.swing.JRadioButtonMenuItem();
        JRBtn_Converter = new javax.swing.JRadioButtonMenuItem();
        JRBtn_Encrypt = new javax.swing.JRadioButtonMenuItem();
        JRBtn_IMC = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JMenu.setText("Menu");

        JBtnG_Menu.add(JRBtn_About);
        JRBtn_About.setSelected(true);
        JRBtn_About.setText("Acerca de");
        JMenu.add(JRBtn_About);

        JBtnG_Menu.add(JRBtn_Arithmetic);
        JRBtn_Arithmetic.setText("Operaciónes aritmeticas");
        JMenu.add(JRBtn_Arithmetic);

        JBtnG_Menu.add(JRBtn_Converter);
        JRBtn_Converter.setText("Convertidor de sistemas");
        JMenu.add(JRBtn_Converter);

        JBtnG_Menu.add(JRBtn_Encrypt);
        JRBtn_Encrypt.setText("Cifrado César");
        JMenu.add(JRBtn_Encrypt);

        JBtnG_Menu.add(JRBtn_IMC);
        JRBtn_IMC.setText("IMC");
        JMenu.add(JRBtn_IMC);

        JMenuBar.add(JMenu);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBtnG_Menu;
    private javax.swing.JMenu JMenu;
    private javax.swing.JMenuBar JMenuBar;
    public javax.swing.JRadioButtonMenuItem JRBtn_About;
    public javax.swing.JRadioButtonMenuItem JRBtn_Arithmetic;
    public javax.swing.JRadioButtonMenuItem JRBtn_Converter;
    public javax.swing.JRadioButtonMenuItem JRBtn_Encrypt;
    public javax.swing.JRadioButtonMenuItem JRBtn_IMC;
    // End of variables declaration//GEN-END:variables
}
