/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author panda
 */
public class ViewArithmetic extends javax.swing.JPanel {

    /**
     * Creates new form ViewArithmetic
     */
    public ViewArithmetic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JL_Numero1 = new javax.swing.JLabel();
        JL_Numero2 = new javax.swing.JLabel();
        JL_Resultado = new javax.swing.JLabel();
        JBtn_Plus = new javax.swing.JButton();
        JBtn_Minus = new javax.swing.JButton();
        JBtn_Times = new javax.swing.JButton();
        JBtn_Into = new javax.swing.JButton();
        JBtn_Modulo = new javax.swing.JButton();
        JTF_Numero1 = new java.awt.TextField();
        JTF_Numero2 = new java.awt.TextField();
        JTF_Resultado = new java.awt.TextField();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(131, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        JL_Numero1.setText("Número 1");

        JL_Numero2.setText("Número 2");

        JL_Resultado.setText("Resultado");

        JBtn_Plus.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        JBtn_Plus.setText("+");

        JBtn_Minus.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        JBtn_Minus.setText("-");
        JBtn_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_MinusActionPerformed(evt);
            }
        });

        JBtn_Times.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        JBtn_Times.setText("x");

        JBtn_Into.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        JBtn_Into.setText("/");

        JBtn_Modulo.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        JBtn_Modulo.setText("%");

        JTF_Resultado.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JL_Numero2)
                        .addComponent(JL_Numero1)
                        .addComponent(JL_Resultado)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(JBtn_Plus)
                            .addGap(18, 18, 18)
                            .addComponent(JBtn_Minus)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(JBtn_Times)
                            .addGap(18, 18, 18)
                            .addComponent(JBtn_Into)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBtn_Modulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTF_Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTF_Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTF_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JL_Numero1)
                        .addComponent(JTF_Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JL_Numero2)
                        .addComponent(JTF_Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTF_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JL_Resultado))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBtn_Plus)
                        .addComponent(JBtn_Minus)
                        .addComponent(JBtn_Times)
                        .addComponent(JBtn_Into)
                        .addComponent(JBtn_Modulo))
                    .addGap(41, 41, 41)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_MinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_MinusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBtn_Into;
    public javax.swing.JButton JBtn_Minus;
    public javax.swing.JButton JBtn_Modulo;
    public javax.swing.JButton JBtn_Plus;
    public javax.swing.JButton JBtn_Times;
    private javax.swing.JLabel JL_Numero1;
    private javax.swing.JLabel JL_Numero2;
    private javax.swing.JLabel JL_Resultado;
    public java.awt.TextField JTF_Numero1;
    public java.awt.TextField JTF_Numero2;
    public java.awt.TextField JTF_Resultado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
