/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author panda
 */
public class ViewIMC extends javax.swing.JPanel {

    /**
     * Creates new form ViewIMC
     */
    public ViewIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtnG_Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JBtn_IMC = new javax.swing.JButton();
        JL_Weight = new javax.swing.JLabel();
        JL_Height = new javax.swing.JLabel();
        JL_IMC = new javax.swing.JLabel();
        JTF_Weight = new javax.swing.JTextField();
        JTF_Height = new javax.swing.JTextField();
        JTF_IMC = new javax.swing.JTextField();
        JL_M = new javax.swing.JLabel();
        JL_Kg = new javax.swing.JLabel();
        JL_Title = new javax.swing.JLabel();
        JL_Sexo = new javax.swing.JLabel();
        JRBtn_Male = new javax.swing.JRadioButton();
        JRBtn_Female = new javax.swing.JRadioButton();
        JL_Shape = new javax.swing.JLabel();
        JTF_Shape = new javax.swing.JTextField();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(242, 9, 48));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        JBtn_IMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBtn_IMC.setText("Calcular");

        JL_Weight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Weight.setText("Peso");

        JL_Height.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Height.setText("Altura");

        JL_IMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_IMC.setText("IMC");

        JTF_Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_WeightActionPerformed(evt);
            }
        });

        JTF_Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_HeightActionPerformed(evt);
            }
        });

        JTF_IMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTF_IMC.setEnabled(false);

        JL_M.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_M.setText("M");

        JL_Kg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Kg.setText("Kg");

        JL_Title.setBackground(new java.awt.Color(204, 255, 204));
        JL_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL_Title.setText("IMC");

        JL_Sexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Sexo.setText("Sexo");

        JBtnG_Sexo.add(JRBtn_Male);
        JRBtn_Male.setText("Masculino");
        JRBtn_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBtn_MaleActionPerformed(evt);
            }
        });

        JBtnG_Sexo.add(JRBtn_Female);
        JRBtn_Female.setText("Femenino");

        JL_Shape.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Shape.setText("Estado");

        JTF_Shape.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTF_Shape.setEnabled(false);
        JTF_Shape.setFocusable(false);
        JTF_Shape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ShapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JL_Weight)
                                .addComponent(JL_IMC)
                                .addComponent(JL_Height)
                                .addComponent(JL_Sexo)
                                .addComponent(JL_Shape))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTF_Weight)
                                        .addComponent(JTF_Height)
                                        .addComponent(JRBtn_Male)
                                        .addComponent(JRBtn_Female)
                                        .addComponent(JTF_IMC))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JL_M)
                                        .addComponent(JL_Kg)))
                                .addComponent(JTF_Shape, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(JBtn_IMC))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(JL_Title)
                            .addGap(81, 81, 81)))
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JL_Title)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JL_Weight)
                                .addComponent(JTF_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JL_Kg))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JL_Height)
                                .addComponent(JTF_Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JL_M))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(JRBtn_Male)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JRBtn_Female))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(JL_Sexo)))
                            .addGap(18, 18, 18)
                            .addComponent(JTF_IMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(JL_IMC))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JL_Shape)
                        .addComponent(JTF_Shape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addComponent(JBtn_IMC)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_WeightActionPerformed

    private void JTF_HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_HeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_HeightActionPerformed

    private void JRBtn_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBtn_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBtn_MaleActionPerformed

    private void JTF_ShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ShapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ShapeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBtnG_Sexo;
    public javax.swing.JButton JBtn_IMC;
    public javax.swing.JLabel JL_Height;
    public javax.swing.JLabel JL_IMC;
    private javax.swing.JLabel JL_Kg;
    private javax.swing.JLabel JL_M;
    private javax.swing.JLabel JL_Sexo;
    public javax.swing.JLabel JL_Shape;
    private javax.swing.JLabel JL_Title;
    public javax.swing.JLabel JL_Weight;
    public javax.swing.JRadioButton JRBtn_Female;
    public javax.swing.JRadioButton JRBtn_Male;
    public javax.swing.JTextField JTF_Height;
    public javax.swing.JTextField JTF_IMC;
    public javax.swing.JTextField JTF_Shape;
    public javax.swing.JTextField JTF_Weight;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
